export { default as TitlePage } from './titlePage'
export { default as SettingPage } from './settingPage'
export { default as MainGamePage } from './mainGamePage'
export { default as GameoverPage } from './gameOverPage'
export { default as RankPage } from './rankPage'